[package]
name = "graph-visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bitvec = "1.0.1"
clap = { version = "4.5.53", features = ["derive"] }
num-traits = "0.2.19"
petgraph = "0.8.3"
thiserror = "2.0.17"
visgraph = "0.1.0"
